services:
  - type: web
    name: nidal-alrouh-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: yarn install && yarn workspace @nidal-alrouh/backend build && yarn workspace @nidal-alrouh/backend prisma migrate deploy
    startCommand: yarn workspace @nidal-alrouh/backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: HELMET_ENABLED
        value: true
      - key: COOKIE_SECURE
        value: true
